In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv('/content/Uncleaned_Smartphon.csv')

#  **Data Assessing**



> `Summary of the Dataset :`


* I collected a dataset of 1,019 smartphone entries from Smartprix Website through web scraping. Each row represents a phone model and includes 12 columns covering different specifications such as model name, price, rating, SIM type, processor, RAM, battery, display, camera, storage card option, and operating system.
* The dataset has some issues — such as mixed text formats, missing brand names, and inconsistent values — which need to be cleaned and organized before analysis.

**`Manual Assessment`**


---


1. **Quality Issue:**
    1. **model**- some brands are written differently like OPPO in model column `consistency issue`
    2. **price**- has unneccesary 'â‚¹'. `validity issue`
    3. **price**- has ',' between numbers `validity issue`
    5. **ratings**- missing values `completeness issue`
    6. **processor**- has some incorrect value for some phones(row #- 412,433,462,509,513,521,530,550,552,560,561,617,638,684,729,743,750,756,758,779,822,837,838,842,860,894,925,932,935,936,942,963,977,989,1002,1012,1018) `validity issue`
        * Row# 486 has value in ram col `validity issue`
    7. **ram**- Some rows have incorrect value(row# 213, 513,514,445,462,514,521,550,560,617,638,729,743,750,758,759,838,840,860,894,925,932,942,952,953,967,968,989,994,1002,1004,1011,1018) `validity issue`
    8. **battery**-
        * Sometimes charging info is not given `completeness issue`
        * Some rows has incorrect value(row# 145,412,433,445,462,485,486,509,513,521,530,550,552,560,617,638,684,729,743,750,758,838,860,894,919,925,925,935,936,939,952,953,963,967,968,977,989,994,1002,1004,1011,1018,1020.) `validity issue`

    9. **display**-
        * Sometimes freq info is not given `completeness issue`
        * Incorrect value in(row# 6,145,355,412,433,445,462,521,550,560,617,638,729,743,750,758,838,860,894,925,935,936,939,942,952,953,967,968,977,989,1002,1011,1012,1018) `validity issue`

    10. Certain Phones are foldable and this info is scattered `validity issue`
    11. **camera**- words like Dual,Triple,Quad are used to represent no. of cameras and front and rear cameras are seprated by '&' `Not an issue just an obsevation`
        * Many rows have incorrect value(Row# 6,145,199,217,306,404,405,412,427,433,437,445,462,492,511,513,518,530,550,552,560,569,571,582,601,609,617,638,666,675,694,701,729,735,743,750,838,860,894,898,899,916,919,925,939,951,952,953,967,968,989,994,1002,1004,1010,1011,1017,1018,1019) `validity issue`
    12. **card**- sometimes contains info about os and camera `validity issue`
    13. **os**- sometimes contains info bluetooth and fm radio `validity issue`
        * Sometimes contains os version name like 'Android v8.1 (Oreo)' `consistency issue`
    14. Missing value in card,os and rating `completeness issue`
    15. Data type of price and rating is incorrect. `validiy issue`

2. **Tidiness Issue:**
    1. **sim**- can be split 3 cols has_5g,has_NFC,has_IR_Blaster
      2. **ram**- can be split into 3 cols RAM and ROM
      3. **processor** - can be split into processor_name,core and CPU speed.
      4. **batery**- can be split into battery capacity, fast_charging_available
      5. **display**- can be split into size,resolution_width,resolution_height and frequency.
      6. **camera**- can be split into front and rear camera
      7. **card**- can be split into supported and extended_upto

3. One of the major problem with the data which we have scrape is the shifting of some rows.

**`Programatic Assessment`**


---

Right now our data is too much unclean, So we can't be able to do much Programatic assessment.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1019 non-null   int64
 1   model       1019 non-null   object
 2   price       1019 non-null   object
 3   rating      360 non-null    float64
 4   sim         1019 non-null   object
 5   processor   1019 non-null   object
 6   ram         1019 non-null   object
 7   battery     1019 non-null   object
 8   display     1019 non-null   object
 9   camera      1019 non-null   object
 10  card        1009 non-null   object
 11  os          985 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 95.7+ KB

In [ ]:
df.describe()

        Unnamed: 0      rating
count  1019.000000  360.000000
mean    509.000000   73.472222
std     294.304264    5.313493
min       0.000000   54.000000
25%     254.500000   71.000000
50%     509.000000   74.000000
75%     763.500000   77.000000
max    1018.000000   79.000000

In [ ]:
df.duplicated().sum()

np.int64(0)


Once we do a basic level of asssesment than programming assisment will help us more better.

Here, for this DataSet we do the iterative approach. We'll do one level of assessment then one level of cleaning then assessment then cleaning....nd so on.

# **Data Cleaning**
### `Working with Data Quality Issue(Dirty Data)`

In [ ]:
#Make a copy
df1=df.copy()

By order of sevirity, we first go with completeness issue but right now we are not in a situation to do work with completeness issue (fill data etc). So we will go with the 2nd order in sevirity that is validity issue.

In [ ]:
#Define- #Replace all the 'â‚¹' and ',' with ''. Also change its data type to int
#Code
df1['price']=df1['price'].str.replace('â‚¹','').str.replace('₹','').str.replace(',','').astype(int)

In [ ]:
#Test
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1019 non-null   int64
 1   model       1019 non-null   object
 2   price       1019 non-null   int64
 3   rating      360 non-null    float64
 4   sim         1019 non-null   object
 5   processor   1019 non-null   object
 6   ram         1019 non-null   object
 7   battery     1019 non-null   object
 8   display     1019 non-null   object
 9   camera      1019 non-null   object
 10  card        1009 non-null   object
 11  os          985 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 95.7+ KB

In [ ]:
df1.head()

,Unnamed: 0,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,0,Oppo F31 Pro 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
1,1,Oppo F31 Pro Plus 5G,32999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
2,2,Oppo F31 5G,22999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
3,3,OPPO Reno 13 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 128 GB inbuilt",5600 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v15,No FM Radio
4,4,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio

In [ ]:
df1=df1.reset_index()

In [ ]:
df1.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
#Aligning the index column of our data frame with excel sheet so that the row numbers in the assessment match.(As we have listed row no. from the sheet)
df1['index']=df1['index']+2

In [ ]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Oppo F31 Pro 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
1,3,Oppo F31 Pro Plus 5G,32999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
2,4,Oppo F31 5G,22999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
3,5,OPPO Reno 13 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 128 GB inbuilt",5600 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v15,No FM Radio
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
...,...,...,...,...,...,...,...,...,...,...,...,...
1014,1016,Lava Blaze Duo (8GB RAM + 128GB),15999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
1015,1017,Amaq Q20,1199,NaN,"Dual Sim, 3G","Spreadtrum, Single Core, 1.5 MHz Processor","64 MB RAM, 128 MB inbuilt",3000 mAh Battery,"2.4 inches, 128 x 160 px Display",0.3 MP Rear Camera,"Memory Card (Hybrid), upto 8 GB",Symbian v23
1016,1018,Jio Bharat Karbonn K2,975,NaN,"Single Sim, 4G, VoLTE",No Wifi,1000 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1018,1020,Karbonn K444r,1259,NaN,Dual Sim,100 kHz Processor,"32 MB RAM, 42 MB inbuilt",1750 mAh Battery,"2.4 inches, 320 x 240 px Display",0.5 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth

In [ ]:
processor_row=set((412,433,462,509,513,521,530,550,552,560,561,617,638,684,729,743,750,756,758,779,822,837,838,842,860,894,925,932,935,936,942,963,977,989,1002,1012,1018))
ram_row=set((213, 513,514,445,462,514,521,550,560,617,638,729,743,750,758,759,838,840,860,894,925,932,942,952,953,967,968,989,994,1002,1004,1011,1018))
battery_row=set((145,412,433,445,462,485,486,509,513,521,530,550,552,560,617,638,684,729,743,750,758,838,860,894,919,925,925,935,936,939,952,953,963,967,968,977,989,994,1002,1004,1011,1018,1020))
display_row=set((6,145,355,412,433,445,462,521,550,560,617,638,729,743,750,758,838,860,894,925,935,936,939,942,952,953,967,968,977,989,1002,1011,1012,1018))
camera_row=set((6,145,199,217,306,404,405,412,427,433,437,445,462,492,511,513,518,530,550,552,560,569,571,582,601,609,617,638,666,675,694,701,729,735,743,750,838,860,894,898,899,916,919,925,939,951,952,953,967,968,989,994,1002,1004,1010,1011,1017,1018,1019))

In [ ]:
df1[df1['index'].isin(processor_row | ram_row | battery_row | display_row | camera_row)]  #Taking union
#These are those rows in which there is atleast one problem in any col
#Total 87 rows out of 1019 rows

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
197,199,Samsung Galaxy Z Fold 7,174999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
211,213,Apple iPhone 16 Plus,78999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
215,217,Motorola Razr 60 5G,40660,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
...,...,...,...,...,...,...,...,...,...,...,...,...
1010,1012,Karbonn K101i,880,NaN,Dual Sim,No Wifi,100 kHz Processor,"40 MB RAM, 35 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB"
1015,1017,Amaq Q20,1199,NaN,"Dual Sim, 3G","Spreadtrum, Single Core, 1.5 MHz Processor","64 MB RAM, 128 MB inbuilt",3000 mAh Battery,"2.4 inches, 128 x 160 px Display",0.3 MP Rear Camera,"Memory Card (Hybrid), upto 8 GB",Symbian v23
1016,1018,Jio Bharat Karbonn K2,975,NaN,"Single Sim, 4G, VoLTE",No Wifi,1000 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1018,1020,Karbonn K444r,1259,NaN,Dual Sim,100 kHz Processor,"32 MB RAM, 42 MB inbuilt",1750 mAh Battery,"2.4 inches, 320 x 240 px Display",0.5 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth

In [ ]:
df1[df1['index'].isin(processor_row & ram_row & battery_row & display_row & camera_row)]  #intersection
#rows in which all col have problem
#Total 15 rows

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
460,462,Jio Bharat J1 4G,1799,NaN,"Single Sim, 3G, 4G, VoLTE","512 MB RAM, 4 GB inbuilt",2500 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,NaN
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
558,560,Motorola Moto A200,1119,NaN,Dual Sim,"56 MB RAM, 36 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 64 GB",NaN,NaN
615,617,Nokia 2660 Flip,4499,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
636,638,Lava Action 4G,1649,NaN,"Dual Sim, 3G, 4G, VoLTE",1000 mAh Battery,"1.8 inches, 240 x 260 px Display",0.3 MP Rear Camera,Memory Card Supported,Bluetooth,NaN,NaN
727,729,Samsung Guru E1200,774,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
741,743,HMD 150 Music (2025),2149,NaN,Dual Sim,No Wifi,Unisoc 6531F,"8 MB RAM, 8 MB inbuilt",2500 mAh Battery,"2.4 inches, 240 x 320 px Display",QVGA Rear Camera,"Memory Card Supported, upto 32 GB"
748,750,Amaq Q1 4G,2498,NaN,"Dual Sim, 3G, 4G",512 MB RAM,3500 mAh Battery,2.8 inches Display,0.6 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
836,838,Jio Bharat K1 Karbonn,890,NaN,"Single Sim, 3G, 4G, VoLTE",No Wifi,ASR,"512 MB RAM, 4 GB inbuilt",1000 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB"
858,860,Lava Gem Power,1539,NaN,Dual Sim,No 3G,No Wifi,"512 MB RAM, 512 MB inbuilt",2575 mAh Battery,"2.8 inches, 320 x 240 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
892,894,Motorola Moto A70,1699,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"2.4 inches, 320 x 240 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
923,925,Nokia 105 Dual SIM (2019),977,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,Bluetooth,NaN,NaN
987,989,Jmax Gold 2,649,NaN,Dual Sim,No Wifi,"Helio, 1.2 MHz Processor","32 MB RAM, 32 MB inbuilt",3000 mAh Battery,"1.8 inches, 320 x 480 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 16 GB"
1000,1002,iKall I6,899,NaN,Dual Sim,No Wifi,1.3 MHz Processor,"32 MB RAM, 32 MB inbuilt",2500 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 MB"
1016,1018,Jio Bharat Karbonn K2,975,NaN,"Single Sim, 4G, VoLTE",No Wifi,1000 mAh Battery,"1.77 inches, 240 x 320 px Display",0.3 MP Rear Camera,Memory Card Supported,Bluetooth,NaN

In [ ]:
#observation
df1[df1['index'].isin(processor_row & ram_row & battery_row & display_row & camera_row)]['price'].mean()

np.float64(1700.9333333333334)

* Observation:
  * In our Dataset mostle problemetic rows are those which are cheaper, (less then 2000)
  * Also mostly these phones are not smartphone they are feature/keypad phone.
* Our main goal is to do the EDA for the smartphones not keypad phone,So we can drop those rows.

In [ ]:
df1=df1[df1['price']>3000]    #Based on our observation there is no smartphone below 3500
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Oppo F31 Pro 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
1,3,Oppo F31 Pro Plus 5G,32999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
2,4,Oppo F31 5G,22999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
3,5,OPPO Reno 13 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 128 GB inbuilt",5600 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v15,No FM Radio
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
...,...,...,...,...,...,...,...,...,...,...,...,...
1006,1008,Lava Yuva Smart,5899,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Unisoc SC9863A, Octa Core, 1.6 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.75 inches, 720 x 1600 px Display with Water ...",13 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v14
1007,1009,itel Zeno 10 (4GB RAM + 64GB),6499,56.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Octa Core Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.6 inches, 720 x 1612 px Display with Water D...",8 MP Dual Rear & 5 MP Front Camera,Memory Card Supported,Android v14
1011,1013,Vivo Y29 5G (8GB RAM+256GB),18999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",5500 mAh Battery with 44W Fast Charging,"6.68 inches, 720 x 1608 px, 120 Hz Display wit...",50 MP + 0.08 MP Dual Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
1014,1016,Lava Blaze Duo (8GB RAM + 128GB),15999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [ ]:
df1[df1['index'].isin(processor_row & ram_row & battery_row & display_row & camera_row)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
615,617,Nokia 2660 Flip,4499,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera

> **Working with Processor column**:

In [ ]:
#Define
df1[df1['index'].isin(processor_row)] #Rows with problem in processor col

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
431,433,Nokia 235 4G 2024,4069,NaN,"Dual Sim, 3G, 4G, VoLTE",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported
519,521,Nokia 3210 4G (2024),3749,NaN,"Dual Sim, 3G, 4G",No Wifi,"Unisoc T107, 1 GHz Processor","64 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB"
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
615,617,Nokia 2660 Flip,4499,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera

Although we can do shifting but after checking our internet about these phones, we get to know that these are feature phone not smartphone. So we will remove them.

In [ ]:
#code
df1.drop([431,519,615],inplace=True)

/tmp/ipython-input-2174722559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([431,519,615],inplace=True)

In [ ]:
#test
df1[df1['index'].isin(processor_row)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

> **Working with ram column:**

In [ ]:
df1[df1['index'].isin(ram_row)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
211,213,Apple iPhone 16 Plus,78999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
512,514,Apple iPhone 16 Plus (256GB),89900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
757,759,Apple iPhone 16 Plus (512GB),105900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A18, Hexa Core, 4.04 GHz Processor",512 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18

Here only ROM is given not RAm

> **Working with battery column**:

In [ ]:
temp_df=df1[df1['index'].isin(battery_row)]

In [ ]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
917,919,Apple iPhone 12 (256GB),63999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

Define- We required to do the shifting of rows - shift(axis=1) func of pandas will be used

In [ ]:
#code
x=temp_df.iloc[::2,7:].shift(1,axis=1)
x

,battery,display,camera,card,os
143,None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
917,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [ ]:
y=temp_df.iloc[1::2,6:].shift(1,axis=1)
y

,ram,battery,display,camera,card,os
548,None,1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth

Now we have to do this edting in the original DataFrame

In [ ]:
df1.loc[temp_df.index,temp_df.columns[7:]]= x
df1.loc[y.index,y.columns]=y

In [ ]:
#test
df1[df1['index'].isin(battery_row)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",None,1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth
917,919,Apple iPhone 12 (256GB),63999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

> **Working with display cols**

In [ ]:
df1[df1['index'].isin(display_row)]  #there is no problem

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",None,1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth

> **Working with camera column**:

In [ ]:
temp_df2=df1[df1['index'].isin(camera_row)]
temp_df2

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt","6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26,No FM Radio
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
197,199,Samsung Galaxy Z Fold 7,174999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
215,217,Motorola Razr 60 5G,40660,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
304,306,Samsung Galaxy Z Fold 7 (16GB RAM + 1TB),216999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","16 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
402,404,Motorola Razr 50 Ultra,57930,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 165 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
403,405,Lava Agni 3 5G,16999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
425,427,Motorola Razr 60 Ultra,89998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",4700 mAh Battery with 68W Fast Charging,"6.96 inches, 1224 x 2992 px, 165 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
435,437,Samsung Galaxy Z Fold 6,112998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
490,492,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),179999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
509,511,Vivo X Fold 5 5G,149998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
516,518,Google Pixel 9 Pro Fold,137999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",None,1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth
567,569,Lava Blaze Duo,14999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
569,571,Lava Agni 3 5G (8GB RAM + 256GB),20999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
580,582,Samsung Galaxy Z Flip 7 5G,102999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
599,601,Vivo X Fold 3 Pro,159999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
607,609,Motorola Razr 50,39900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
664,666,Infinix Zero Flip 5G,39999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8020, Octa Core, 2.6 GHz Processor","8 GB RAM, 512 GB inbuilt",4720 mAh Battery with 70W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
673,675,Tecno Phantom V Fold 2,89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 512 GB inbuilt",5750 mAh Battery with 70W Fast Charging,"7.85 inches, 2000 x 2296 px, 120 Hz Display","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Android v14
692,694,Samsung Galaxy Z Fold 5,109999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
699,701,Samsung Galaxy Z Flip 5,56899,NaN,"Single Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
733,735,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
896,898,Samsung Galaxy Z Fold 4,137845,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
897,899,Samsung Galaxy Z Flip 4 5G,62990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
914,916,Samsung Galaxy Z Flip 3,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
917,919,Apple iPhone 12 (256GB),63999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
949,951,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),114999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [ ]:
#Define- Shifting the 4th index row towards right from battery col
#code
z=temp_df2.iloc[0:1,7:].shift(1,axis=1)
z

,battery,display,camera,card,os
4,None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26

In [ ]:
#Assigning it to the original dataframe
df1.loc[z.index,z.columns]=z

In [ ]:
#Test
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Oppo F31 Pro 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
1,3,Oppo F31 Pro Plus 5G,32999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
2,4,Oppo F31 5G,22999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
3,5,OPPO Reno 13 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 128 GB inbuilt",5600 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v15,No FM Radio
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
...,...,...,...,...,...,...,...,...,...,...,...,...
1006,1008,Lava Yuva Smart,5899,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Unisoc SC9863A, Octa Core, 1.6 GHz Processor","3 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.75 inches, 720 x 1600 px Display with Water ...",13 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v14
1007,1009,itel Zeno 10 (4GB RAM + 64GB),6499,56.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Octa Core Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.6 inches, 720 x 1612 px Display with Water D...",8 MP Dual Rear & 5 MP Front Camera,Memory Card Supported,Android v14
1011,1013,Vivo Y29 5G (8GB RAM+256GB),18999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",5500 mAh Battery with 44W Fast Charging,"6.68 inches, 720 x 1608 px, 120 Hz Display wit...",50 MP + 0.08 MP Dual Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 1 TB",Android v14
1014,1016,Lava Blaze Duo (8GB RAM + 128GB),15999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [ ]:
#Rows with no problem in camera section
temp_df2[temp_df2['camera'].str.contains('MP')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",None,1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth
917,919,Apple iPhone 12 (256GB),63999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [ ]:
temp_df2[temp_df2['camera'].str.contains('MP')].shape

(4, 12)

In [ ]:
#Smartphones with problem in camera
temp_df2[~temp_df2['camera'].str.contains('MP')].shape

(25, 12)

In [ ]:
temp_df2=temp_df2[~temp_df2['camera'].str.contains('MP')]

In [ ]:
temp_df2

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
197,199,Samsung Galaxy Z Fold 7,174999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
215,217,Motorola Razr 60 5G,40660,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
304,306,Samsung Galaxy Z Fold 7 (16GB RAM + 1TB),216999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","16 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
402,404,Motorola Razr 50 Ultra,57930,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 165 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
403,405,Lava Agni 3 5G,16999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
425,427,Motorola Razr 60 Ultra,89998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",4700 mAh Battery with 68W Fast Charging,"6.96 inches, 1224 x 2992 px, 165 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
435,437,Samsung Galaxy Z Fold 6,112998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
490,492,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),179999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
509,511,Vivo X Fold 5 5G,149998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
516,518,Google Pixel 9 Pro Fold,137999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
567,569,Lava Blaze Duo,14999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
569,571,Lava Agni 3 5G (8GB RAM + 256GB),20999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",Dual Display,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
580,582,Samsung Galaxy Z Flip 7 5G,102999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
599,601,Vivo X Fold 3 Pro,159999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
607,609,Motorola Razr 50,39900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
664,666,Infinix Zero Flip 5G,39999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8020, Octa Core, 2.6 GHz Processor","8 GB RAM, 512 GB inbuilt",4720 mAh Battery with 70W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
673,675,Tecno Phantom V Fold 2,89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 512 GB inbuilt",5750 mAh Battery with 70W Fast Charging,"7.85 inches, 2000 x 2296 px, 120 Hz Display","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Android v14
692,694,Samsung Galaxy Z Fold 5,109999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
699,701,Samsung Galaxy Z Flip 5,56899,NaN,"Single Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
733,735,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
896,898,Samsung Galaxy Z Fold 4,137845,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
897,899,Samsung Galaxy Z Flip 4 5G,62990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
914,916,Samsung Galaxy Z Flip 3,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
949,951,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),114999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [ ]:
#Define- In df1, we have to put the value of card column in camera column from temp_df2
#code
df1.loc[temp_df2.index,'camera']=temp_df2['card'].values

In [ ]:
#test
df1[df1['index'].isin(camera_row)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
4,6,Apple iPhone 17,82900,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 256 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
143,145,Apple iPhone 17 (512GB),102900,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Apple A19, Hexa Core Processor","8 GB RAM, 512 GB inbuilt",None,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP Dual Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26
197,199,Samsung Galaxy Z Fold 7,174999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
215,217,Motorola Razr 60 5G,40660,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
304,306,Samsung Galaxy Z Fold 7 (16GB RAM + 1TB),216999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","16 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
402,404,Motorola Razr 50 Ultra,57930,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 165 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
403,405,Lava Agni 3 5G,16999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
425,427,Motorola Razr 60 Ultra,89998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",4700 mAh Battery with 68W Fast Charging,"6.96 inches, 1224 x 2992 px, 165 Hz Display wi...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
435,437,Samsung Galaxy Z Fold 6,112998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
490,492,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),179999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
509,511,Vivo X Fold 5 5G,149998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
516,518,Google Pixel 9 Pro Fold,137999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
548,550,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",None,1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth
567,569,Lava Blaze Duo,14999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
569,571,Lava Agni 3 5G (8GB RAM + 256GB),20999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
580,582,Samsung Galaxy Z Flip 7 5G,102999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
599,601,Vivo X Fold 3 Pro,159999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
607,609,Motorola Razr 50,39900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
664,666,Infinix Zero Flip 5G,39999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8020, Octa Core, 2.6 GHz Processor","8 GB RAM, 512 GB inbuilt",4720 mAh Battery with 70W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
673,675,Tecno Phantom V Fold 2,89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 512 GB inbuilt",5750 mAh Battery with 70W Fast Charging,"7.85 inches, 2000 x 2296 px, 120 Hz Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Android v14
692,694,Samsung Galaxy Z Fold 5,109999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
699,701,Samsung Galaxy Z Flip 5,56899,NaN,"Single Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
733,735,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
896,898,Samsung Galaxy Z Fold 4,137845,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
897,899,Samsung Galaxy Z Flip 4 5G,62990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
914,916,Samsung Galaxy Z Flip 3,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
917,919,Apple iPhone 12 (256GB),63999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
949,951,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),114999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [ ]:
pd.set_option('display.max_rows',None)   #To see all the rows without trunctation
df['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                             74
50 MP + 2 MP Dual Rear & 16 MP Front Camera                            53
0.3 MP Rear Camera                                                     42
50 MP + 8 MP Dual Rear & 16 MP Front Camera                            33
50 MP + 2 MP Dual Rear & 32 MP Front Camera                            26
Foldable Display, Dual Display                                         24
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   22
50 MP + 8 MP Dual Rear & 32 MP Front Camera                            21
50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front Camera                   21
50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                  19
50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                   18
50 MP + 8 MP Dual Rear & 50 MP Front Camera                            18
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                  16
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                 16
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   16
50 MP + 50 MP Dual Rear & 50 MP Front Camera                           14
50 MP + 12 MP + 10 MP Triple Rear & 12 MP Front Camera                 13
50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                   12
50 MP Dual Rear & 8 MP Front Camera                                    12
64 MP + 2 MP Dual Rear & 16 MP Front Camera                            12
50 MP Rear & 8 MP Front Camera                                         10
48 MP + 12 MP Dual Rear & 12 MP Front Camera                           10
50 MP + 0.08 MP Dual Rear & 8 MP Front Camera                          10
No Rear Camera                                                         10
32 MP Dual Rear & 8 MP Front Camera                                     9
13 MP Rear & 5 MP Front Camera                                          9
50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                  9
50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                    9
50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                    9
200 MP Quad Rear & 12 MP Front Camera                                   8
50 MP + 13 MP Dual Rear & 32 MP Front Camera                            8
13 MP Dual Rear & 5 MP Front Camera                                     8
50 MP + 2 MP Dual Rear & 5 MP Front Camera                              8
50 MP Dual Rear & 5 MP Front Camera                                     8
Memory Card Supported, upto 32 GB                                       8
32 MP Rear & 5 MP Front Camera                                          7
48 MP + 48 MP + 48 MP Triple Rear & 18 MP Front Camera                  7
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   6
108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                   6
Bluetooth                                                               6
108 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                   6
50 MP + 50 MP + 8 MP Triple Rear & 16 MP Front Camera                   6
50 MP + 8 MP Dual Rear & 20 MP Front Camera                             6
50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                   6
12 MP + 12 MP Dual Rear & 12 MP Front Camera                            6
48 MP + 48 MP + 12 MP Triple Rear & 12 MP Front Camera                  6
13 MP Rear & 8 MP Front Camera                                          5
50 MP + 50 MP Dual Rear & 32 MP Front Camera                            5
50 MP + 48 MP + 48 MP Triple Rear & 42 MP Front Camera                  5
13 MP + 0.08 MP Dual Rear & 5 MP Front Camera                           5
200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   5
64 MP Quad Rear & 32 MP Front Camera                                    5
Dual Display                                                            5
32 MP Rear & 8 MP Front Camera                                          4
50 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                   4
64 MP + 8 MP Dual Rear & 13 MP Front Camera                             4
50 MP + 2 MP Triple Rear & 16 MP Front Camera                           4
8 MP Rear & 5 MP Front Camera                                           4
12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front Camera                   4
50 MP + 12 MP + 8 MP Triple Rear & 10 MP Front Camera                   4
50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                   4
50 MP + 50 MP + 10 MP Triple Rear & 50 MP Front Camera                  4
50 MP + 2 MP Dual Rear & 50 MP Front Camera                             4
50 MP Rear & 5 MP Front Camera                                          4
50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32 MP Dual Front Camera     4
48 MP Dual Rear & 8 MP Front Camera                                     4
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                     4
48 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                    4
64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                    4
64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                    4
2.4 inches, 240 x 320 px Display                                        4
50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front Camera                    4
48 MP Rear & 18 MP Front Camera                                         3
50 MP + 50 MP + 8 MP Triple Rear & 20 MP Front Camera                   3
50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front Camera                   3
64 MP + 13 MP Dual Rear & 13 MP Front Camera                            3
50 MP + 50 MP + 12 MP Triple Rear & 50 MP Front Camera                  3
48 MP Rear & 12 MP Front Camera                                         3
50 MP + 50 MP Dual Rear & 16 MP Front Camera                            3
50 MP Quad Rear & 32 MP Front Camera                                    3
8 MP + 0.08 MP Dual Rear & 5 MP Front Camera                            3
50 MP + Depth Sensor Dual Rear & 5 MP Front Camera                      3
50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front Camera                    3
108 MP + 2 MP Dual Rear & 8 MP Front Camera                             3
Memory Card Not Supported                                               3
64 MP + 2 MP Dual Rear & 8 MP Front Camera                              3
64 MP + 2 MP Dual Rear & 13 MP Front Camera                             3
64 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                    3
48 MP Quad Rear & 16 MP Front Camera                                    3
108 MP + 2 MP Dual Rear & 16 MP Front Camera                            3
64 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                    3
64 MP Quad Rear & 13 MP Front Camera                                    2
50 MP + 12 MP + 8 MP Triple Rear & 50 MP Front Camera                   2
32 MP + 2 MP Dual Rear & 8 MP Front Camera                              2
50 MP + 12 MP Dual Rear & 8 MP Front Camera                             2
64 MP + 8 MP Dual Rear & 50 MP Front Camera                             2
13 MP + 2 MP Dual Rear & 5 MP Front Camera                              2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP Front Camera                  2
Memory Card Supported                                                   2
50 MP + 2 MP + 0.08 MP Triple Rear & 50 MP Front Camera                 2
50 MP + 48 MP + 12 MP Triple Rear & 11.1 MP Front Camera                2
108 MP + 2 MP Triple Rear & 8 MP Front Camera                           2
50 MP + 13 MP + 10 MP Triple Rear & 32 MP Front Camera                  2
108 MP + 8 MP Dual Rear & 13 MP Front Camera                            2
108 MP + 2 MP Dual Rear & 13 MP Front Camera                            2
50 MP + 2 MP Dual Rear & 20 MP Front Camera                             2
50 MP + 2 MP Dual Rear & 13 MP Front Camera                             2
50 MP + 13 MP + 10 MP Triple Rear & 50 MP Front Camera                  2
64 MP + AI Camera Dual Rear & 13 MP Front Camera                        2
64 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera                  2
50 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                    2
50 MP Dual Rear & 13 MP Front Camera                                    2
64 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                   2
50 MP + 48 MP + 32 MP Triple Rear & 16 MP Front Camera                  2
1.8 inches, 128 x 160 px Display                                        2
64 MP + 5 MP Dual Rear & 13 MP Front Camera                             2
50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                    2
50 MP + Ultra Wide Dual Rear & 5 MP Front Camera                        2
2.8 inches, 240 x 320 px Display                                        2
48 MP Quad Rear & 13 MP Front Camera                                    2
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                    2
64 MP + 12 MP + 12 MP Triple Rear & 10 MP Front Camera                  2
64 MP Quad Rear & 16 MP Front Camera                                    2
0.5 MP Rear Camera                                                      2
1.3 MP Rear Camera                                                      2
1.8 inches, 320 x 480 px Display                                        2
50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                     2
108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                   2
48 MP Quad Rear & 8 MP Front Camera                                     2
8 MP Dual Rear & 5 MP Front Camera                                      2
5 MP Rear Camera                                                        2
48 MP + Depth Sensor Dual Rear & 8 MP Front Camera                      2
Memory Card Supported, upto 128 GB                                      2
200 MP + 12 MP Dual Rear & 12 MP Front Camera                           2
108 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                  2
64 MP + 5 MP + 2 MP Triple Rear & 50 MP Front Camera                    1
50 MP + Depth Sensor Dual Rear & 8 MP Front Camera                      1
12.2 MP + 12 MP Dual Rear & 8 MP Front Camera                           1
50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Front Camera                1
64 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                  1
50 MP + 48 MP + 48 MP Triple Rear & 10.5 MP Front Camera                1
108 MP + 5 MP Dual Rear & 16 MP Front Camera                            1
48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP Front Camera              1
48 MP + 13 MP Dual Rear & 13 MP Front Camera                            1
200 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                 1
108 MP + Macro Dual Rear & 13 MP Front Camera                           1
50 MP + 48 MP Dual Rear & 10.5 MP Front Camera                          1
QVGA Rear Camera                                                        1
108 MP Quad Rear & 40 MP Front Camera                                   1
108 MP + 2 MP Dual Rear & 50 MP Front Camera                            1
50 MP + 12 MP Dual Rear & 10.5 MP Front Camera                          1
64 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                    1
Memory Card Supported, upto 64 GB                                       1
16 MP Rear & 5 MP Front Camera                                          1
50 MP + 12 MP Dual Rear & 10.8 MP Front Camera                          1
64 MP + 50 MP + 50 MP Triple Rear & 16 MP Front Camera                  1
108 MP + 13 MP + 2 MP Triple Rear & 50 MP Front Camera                  1
108 MP + 2 MP Triple Rear & 16 MP Front Camera                          1
108 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front Camera                   1
48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 50 MP + 12 MP Triple Rear & 50 MP + 2 MP Dual Front Camera      1
8 MP Rear & 8 MP Front Camera                                           1
12 MP Quad Rear & 10 MP Front Camera                                    1
64 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                   1
50 MP + Depth Sensor + Macro Triple Rear & 5 MP Front Camera            1
108 MP + 5 MP + 2 MP Triple Rear & 50 MP Front Camera                   1
64 MP Quad Rear & 20 MP Front Camera                                    1
48 MP Quad Rear & 20 MP Front Camera                                    1
48 MP + 13 MP + 13 MP Triple Rear & 16 MP Front Camera                  1
50 MP + 16 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 50 MP + 12 MP Triple Rear & 32 MP Front Camera                  1
Digital Rear Camera                                                     1
2 MP Rear & 0.3 MP Front Camera                                         1
20 MP + 12 MP Dual Rear & 20 MP Front Camera                            1
50 MP + Ultra Wide + Macro Triple Rear & 8 MP Front Camera              1
64 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                   1
108 MP Quad Rear & 32 MP Front Camera                                   1
48 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                    1
50 MP + 32 MP + 8 MP Triple Rear & 16 MP Front Camera                   1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                  1
13 MP Rear & Main Front Camera                                          1
108 MP + 5 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP Quad Rear & 16 MP Front Camera                                    1
1.77 inches, 240 x 320 px Display                                       1
108 MP + 0.08 MP Dual Rear & 8 MP Front Camera                          1
13 MP + 2 MP Dual Rear & 8 MP Front Camera                              1
108 MP + 50 MP + 13 MP Triple Rear & 50 MP Front Camera                 1
No FM Radio                                                             1
5 MP Rear & Main Front Camera                                           1
64 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                    1
50 MP + 12 MP + 12 MP Triple Rear & 32 MP Front Camera                  1
50 MP Quad Rear & 13 MP Front Camera                                    1
64 MP + 13 MP + 5 MP Triple Rear & 24 MP Front Camera                   1
64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                    1
48 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                     1
108 MP + 8 MP + 2 MP Triple Rear & 50 MP + 8 MP Dual Front Camera       1
2.8 inches, 320 x 240 px Display                                        1
50 MP + 50 MP + 13 MP Triple Rear & 32 MP Front Camera                  1
48 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                    1
48 MP Quad Rear & 32 MP Front Camera                                    1
64 MP + 8 MP + 2 MP Triple Rear & 44 MP + 8 MP Dual Front Camera        1
12 MP + 5 MP Dual Rear & 20 MP + 2 MP Dual Front Camera                 1
1.2 inches, 120 x 240 px Display                                        1
12 MP + 5 MP Dual Rear & 20 MP Front Camera                             1
12 MP + 12 MP Dual Rear & 7 MP Front Camera                             1
0.66 inches, 128 x 160 px Display                                       1
2.8 inches, 128 x 160 px Display                                        1
0.8 MP Rear Camera                                                      1
2500 mAh Battery with Fast Charging                                     1
50 MP + 5 MP Dual Rear & 8 MP Front Camera                              1
Memory Card (Hybrid), upto 8 GB                                         1
VGA Rear Camera                                                         1
Memory Card (Hybrid)                                                    1
0.6 MP Rear Camera                                                      1
Name: count, dtype: int64

> **Working with card column:**

In [ ]:
#Programatic assessment
df1['card'].value_counts()

card
Memory Card Not Supported                                                  184
Memory Card (Hybrid), upto 1 TB                                            159
Android v15                                                                119
Android v14                                                                 83
Memory Card Supported, upto 1 TB                                            78
Memory Card (Hybrid), upto 2 TB                                             62
Memory Card (Hybrid)                                                        43
Android v12                                                                 30
Memory Card Supported, upto 2 TB                                            26
Android v13                                                                 24
Memory Card Supported                                                       20
Memory Card Supported, upto 512 GB                                          19
Memory Card (Hybrid), upto 1.5 TB                                           14
Android v11                                                                  9
Memory Card Supported, upto 256 GB                                           5
50 MP + 12 MP Dual Rear & 10 MP Front Camera                                 5
Android v10                                                                  4
Memory Card (Hybrid), upto 256 GB                                            4
200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 10 MP Dual Front Camera         3
Android v16                                                                  3
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                 3
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera           3
50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front Camera                         2
50 MP + 13 MP Dual Rear & 32 MP Front Camera                                 2
Memory Card Supported, upto 128 GB                                           2
50 MP + 50 MP Dual Rear & 50 MP Front Camera                                 2
64 MP + 2 MP Dual Rear & 16 MP Front Camera                                  2
Memory Card Supported, upto 32 GB                                            2
50 MP + 50 MP Dual Rear & 32 MP Front Camera                                 1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera          1
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP Dual Front Camera      1
50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera          1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera          1
Android v10.1                                                                1
64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20 MP Dual Front Camera          1
Memory Card (Hybrid), upto 128 GB                                            1
Name: count, dtype: int64

In [ ]:
#Define- Replacing the camera value in card column with 'Memory Card Not Supported'
#code
temp_df3=df1[df1['card'].str.contains('MP')]
temp_df3

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
197,199,Samsung Galaxy Z Fold 7,174999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
215,217,Motorola Razr 60 5G,40660,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7400X, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 30W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
304,306,Samsung Galaxy Z Fold 7 (16GB RAM + 1TB),216999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","16 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
402,404,Motorola Razr 50 Ultra,57930,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 165 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,50 MP + 50 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
403,405,Lava Agni 3 5G,16999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
425,427,Motorola Razr 60 Ultra,89998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","16 GB RAM, 512 GB inbuilt",4700 mAh Battery with 68W Fast Charging,"6.96 inches, 1224 x 2992 px, 165 Hz Display wi...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
435,437,Samsung Galaxy Z Fold 6,112998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
490,492,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),179999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
509,511,Vivo X Fold 5 5G,149998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
516,518,Google Pixel 9 Pro Fold,137999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
567,569,Lava Blaze Duo,14999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 2 MP Dual Rear & 16 MP Front Camera,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
569,571,Lava Agni 3 5G (8GB RAM + 256GB),20999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 66W Fast Charging,"6.78 inches, 1200 x 2652 px, 120 Hz Display wi...",50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported
580,582,Samsung Galaxy Z Flip 7 5G,102999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
599,601,Vivo X Fold 3 Pro,159999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
607,609,Motorola Razr 50,39900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
664,666,Infinix Zero Flip 5G,39999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8020, Octa Core, 2.6 GHz Processor","8 GB RAM, 512 GB inbuilt",4720 mAh Battery with 70W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,50 MP + 50 MP Dual Rear & 50 MP Front Camera,Memory Card Not Supported
673,675,Tecno Phantom V Fold 2,89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 512 GB inbuilt",5750 mAh Battery with 70W Fast Charging,"7.85 inches, 2000 x 2296 px, 120 Hz Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Android v14
684,686,Samsung Galaxy Z Flip 6 5G,74900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
692,694,Samsung Galaxy Z Fold 5,109999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
699,701,Samsung Galaxy Z Flip 5,56899,NaN,"Single Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
733,735,Samsung Galaxy Z Flip 7 FE (8GB RAM + 256GB),89999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
771,773,OnePlus Open 5G Apex Edition,149998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
896,898,Samsung Galaxy Z Fold 4,137845,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
897,899,Samsung Galaxy Z Flip 4 5G,62990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
914,916,Samsung Galaxy Z Flip 3,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
949,951,Samsung Galaxy Z Flip 7 5G (12GB RAM+512GB),114999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1014,1016,Lava Blaze Duo (8GB RAM + 128GB),15999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi","Dimensity 7025, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,64 MP + 2 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported
1017,1019,Samsung Galaxy Z Flip 7 FE 5G,84999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [ ]:
df1.loc[temp_df3.index,'card']='Memory card not supported'

In [ ]:
#Test
df1['card'].value_counts()

card
Memory Card Not Supported             184
Memory Card (Hybrid), upto 1 TB       159
Android v15                           119
Android v14                            83
Memory Card Supported, upto 1 TB       78
Memory Card (Hybrid), upto 2 TB        62
Memory Card (Hybrid)                   43
Android v12                            30
Memory card not supported              28
Memory Card Supported, upto 2 TB       26
Android v13                            24
Memory Card Supported                  20
Memory Card Supported, upto 512 GB     19
Memory Card (Hybrid), upto 1.5 TB      14
Android v11                             9
Memory Card Supported, upto 256 GB      5
Memory Card (Hybrid), upto 256 GB       4
Android v10                             4
Android v16                             3
Memory Card Supported, upto 32 GB       2
Memory Card Supported, upto 128 GB      2
Android v10.1                           1
Memory Card (Hybrid), upto 128 GB       1
Name: count, dtype: int64

In [ ]:
#Rows with defect value in card column
temp_df=df1[~df1['card'].str.contains('Memory')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Oppo F31 Pro 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
1,3,Oppo F31 Pro Plus 5G,32999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
2,4,Oppo F31 5G,22999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
3,5,OPPO Reno 13 5G,26999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 128 GB inbuilt",5600 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v15,No FM Radio
5,7,Vivo T4 Pro 5G,27782,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v15,No FM Radio
9,11,Motorola Edge 60 Pro,28332,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
17,19,OnePlus Nord 5 5G,31998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",6800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
18,20,Google Pixel 9,51360,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Tensor G4, Octa Core, 3.1 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 27W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",50 MP + 48 MP Dual Rear & 10.5 MP Front Camera,Android v14,No FM Radio
20,22,OPPO Reno 14 5G,37998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v15,No FM Radio
25,27,Samsung Galaxy S24 5G,49450,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v14,No FM Radio
27,29,Oppo K13,17068,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
29,31,Oppo F31 Pro 5G (12GB RAM + 256GB),30999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
30,32,Nothing Phone 3 5G,44899,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5500 mAh Battery with 65W Fast Charging,"6.67 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
31,33,iQOO Neo 10R,24999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",6400 mAh Battery with 80W Fast Charging,"6.78 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
35,37,Realme P4 Pro 5G,23499,73.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7 Gen 4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
38,40,iQOO Neo 10,31998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.78 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
39,41,Nothing Phone 3a,21290,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 50W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front...,Android v15,No FM Radio
40,42,Oppo F31 Pro 5G (8GB RAM + 256GB),28999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
41,43,Poco X7 Pro 5G,25490,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","8 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
42,44,OPPO Reno 13 Pro 5G,36999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v15,No FM Radio
46,48,OPPO Reno 14 Pro 5G,49998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8450, Octa Core, 3.25 GHz Processor","12 GB RAM, 256 GB inbuilt",6200 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
48,50,Samsung Galaxy S25 5G,68900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8Elite, Octa Core, 4.47 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v15,No FM Radio
50,52,Vivo T3 Ultra,24499,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 9200 Plus, Octa Core, 3.35 GHz Proce...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 80W Fast Charging,"6.78 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v14,No FM Radio
54,56,Honor 200,19998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","8 GB RAM, 256 GB inbuilt",5200 mAh Battery with 100W Fast Charging,"6.7 inches, 1200 x 2664 px, 120 Hz Display wit...",50 MP + 50 MP + 12 MP Triple Rear & 50 MP Fron...,Android v14,No FM Radio
56,58,Vivo Y31 5G,14999,61.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core Processor","4 GB RAM, 128 GB inbuilt",6500 mAh Battery with 44W Fast Charging,"6.68 inches, 720 x 1620 px, 120 Hz Display wit...",50 MP + 0.08 MP Dual Rear & 8 MP Front Camera,Android v15,Bluetooth
58,60,Realme P4 5G,18499,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.77 inches, 1080 x 2392 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
62,64,Xiaomi 14 Civi,27999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 67W Fast Charging,"6.55 inches, 1236 x 2750 px, 120 Hz Display wi...",50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32...,Android v14,No FM Radio
64,66,iQOO Z10x,13498,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",6500 mAh Battery with 44W Fast Charging,"6.72 inches, 1080 x 2408 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v15,No FM Radio
66,68,Realme 15 Pro 5G,31999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
67,69,Realme P3 5G,16124,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
70,72,OPPO Reno 13 Pro 5G (12GB RAM + 512GB),54999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v15,No FM Radio
75,77,iQOO 13 5G,54998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 120W Fast Charging,"6.82 inches, 1440 x 3168 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Android v15,No FM Radio
76,78,Xiaomi Redmi Note 14 Pro 5G,19989,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 7300 Ultra, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front ...,Android v14,No FM Radio
80,82,Vivo Y400 Pro 5G,24998,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
82,84,Motorola Edge 60 Pro (16GB RAM + 512GB),38949,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
85,87,OPPO Reno 13 5G (8GB+256GB),30640,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 256 GB inbuilt",5600 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v15,No FM Radio
87,89,Samsung Galaxy A56 5G,35999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Exynos 1580, Octa Core, 2.9 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front...,Android v15,No FM Radio
91,93,Oppo F31 Pro Plus 5G (12GB RAM + 256GB),34999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
92,94,Tecno Pova Slim 5G,19999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6400, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.78 inches, 1224 x 2720 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 13 MP Front Camera,Android v15,No FM Radio
93,95,Google Pixel 10 5G,66498,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",Tensor G5,"12 GB RAM, 256 GB inbuilt",4970 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Android v16,No FM Radio
94,96,Vivo T4 Pro 5G (8GB RAM + 256GB),29899,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR B...","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v15,No FM Radio
97,99,Samsung Galaxy A36 5G,28499,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front ...,Android v15,No FM Radio
100,102,Infinix Note 50s 5G,15999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7300 Ultimate, Octa Core, 2.5 GHz Pr...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.78 inches, 1080 x 2436 px, 144 Hz Display wi...",64 MP + 2 MP Dual Rear & 13 MP Front Camera,Android v15,Bluetooth
101,103,Oppo F31 5G (8GB RAM + 256GB),24999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6300, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2412 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
113,115,Vivo Y31 Pro 5G (8GB RAM + 256GB),20999,68.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7300, Octa Core Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 44W Fast Charging,"6.72 inches, 1080 x 2408 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v15,No FM Radio
114,116,Xiaomi 14 Civi (12GB RAM + 512GB),30999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4700 mAh Battery with 67W Fast Charging,"6.55 inches, 1236 x 2750 px, 120 Hz Display wi...",50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32...,Android v14,No FM Radio
115,117,Realme Narzo 80 Pro 5G,17498,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7400, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.72 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
117,119,Motorola Edge 60 Pro (12GB RAM + 256GB),30962,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
121,123,Samsung Galaxy S24 Plus,59999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Exynos 2400, Deca Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4900 mAh Battery with 45W Fast Charging,"6.7 inches, 1440 x 3120 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v14,No FM Radio
122,124,iQOO Z10 Lite,9998,71.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",6000 mAh Battery with 15W Fast Charging,"6.74 inches, 720 x 1600 px, 90 Hz Display",50 MP + 2 MP Dual Rear & 5 MP Front Camera,Android v15,Bluetooth
124,126,Oppo F27 Pro Plus 5G,20800,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",64 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v14,No FM Radio
125,127,Vivo Y400 5G,21998,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 4 Gen2, Octa Core, 2.2 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
127,129,Infinix GT 30 Pro,23500,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8350 Ultimate, Octa Core, 3.35 GHz P...","8 GB RAM, 256 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.78 inches, 1224 x 2720 px, 144 Hz Display wi...",108 MP + 8 MP Dual Rear & 13 MP Front Camera,Android v15,Bluetooth
130,132,iQOO Neo 10 (12GB RAM + 256GB),35998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.78 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
133,135,OnePlus 12R,32994,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 100W Fast Charging,"6.78 inches, 1264 x 2780 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v14,No FM Radio
135,137,OnePlus Nord 5 (12GB RAM + 512GB),37998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",6800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
138,140,Realme P3 Pro 5G,19999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
139,141,Oppo F29 Pro 5G,23999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 7300, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v14,No FM Radio
140,142,Poco X7 5G,17999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC,...","Dimensity 7300 Ultra, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front ...,Android v14,No FM Radio
145,147,Google Pixel 10 Pro,102990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",Tensor G5,"16 GB RAM, 256 GB inbuilt",4870 mAh Battery with 30W Fast Charging,"6.3 inches, 1280 x 2856 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Android v16,No FM Radio
146,148,Oppo K13 (8GB RAM + 256GB),19781,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio

In [ ]:
#define- Putting the value of card column in os column
#code
df1.loc[temp_df.index,'os']=temp_df['card'].values

In [ ]:
#test
df1['os'].value_counts()

os
Android v14                  314
Android v15                  308
Android v13                  104
Android v12                   67
Android v11                   38
Memory Card Not Supported     19
iOS v18                       15
iOS v26                       12
Android v10                    9
Android v16                    6
iOS v17                        4
Android v9.0 (Pie)             4
Android v8.1 (Oreo)            3
iOS v16                        3
iOS v15                        2
Android 14 Go Edition          2
Android v10.0                  1
Android 15 Go                  1
iOS v13                        1
Bluetooth                      1
Android v10.1                  1
KAI OS                         1
S30+                           1
iOS v14                        1
Android v7.1.2 (Nougat)        1
iOS v11                        1
Name: count, dtype: int64

In [ ]:
#define- Replacing the rows with not word 'memory' in card cols with 'Memory Card Not Supported'
#code
df1.loc[temp_df.index,'card']='Memory Card Not Supported'

In [ ]:
#test
df1['card'].value_counts()

card
Memory Card Not Supported             457
Memory Card (Hybrid), upto 1 TB       159
Memory Card Supported, upto 1 TB       78
Memory Card (Hybrid), upto 2 TB        62
Memory Card (Hybrid)                   43
Memory card not supported              28
Memory Card Supported, upto 2 TB       26
Memory Card Supported                  20
Memory Card Supported, upto 512 GB     19
Memory Card (Hybrid), upto 1.5 TB      14
Memory Card Supported, upto 256 GB      5
Memory Card (Hybrid), upto 256 GB       4
Memory Card Supported, upto 32 GB       2
Memory Card Supported, upto 128 GB      2
Memory Card (Hybrid), upto 128 GB       1
Name: count, dtype: int64

> **Working with os column**:

In [ ]:
df1['os'].value_counts()

os
Android v14                  314
Android v15                  308
Android v13                  104
Android v12                   67
Android v11                   38
Memory Card Not Supported     19
iOS v18                       15
iOS v26                       12
Android v10                    9
Android v16                    6
iOS v17                        4
Android v9.0 (Pie)             4
Android v8.1 (Oreo)            3
iOS v16                        3
iOS v15                        2
Android 14 Go Edition          2
Android v10.0                  1
Android 15 Go                  1
iOS v13                        1
Bluetooth                      1
Android v10.1                  1
KAI OS                         1
S30+                           1
iOS v14                        1
Android v7.1.2 (Nougat)        1
iOS v11                        1
Name: count, dtype: int64

In [ ]:
temp_df=temp_df = df1[df1['os'].str.contains('Memory|Bluetooth',na=False)]     #df1[df1['os'].str.contains('Memory'|'Bluetooth')] does a bitwise OR between strings, which isn’t valid.
                                                                               #na=False avoids errors if there are NaN values in the column

In [ ]:
#Define-Replacing rows with 'Memory' and 'Bluetooth' in os section with nan value
#code
df1.loc[temp_df.index,'os']=np.nan

In [ ]:
#test
df1['os'].value_counts()

os
Android v14                314
Android v15                308
Android v13                104
Android v12                 67
Android v11                 38
iOS v18                     15
iOS v26                     12
Android v10                  9
Android v16                  6
iOS v17                      4
Android v9.0 (Pie)           4
iOS v16                      3
Android v8.1 (Oreo)          3
iOS v15                      2
Android 14 Go Edition        2
Android 15 Go                1
iOS v13                      1
Android v10.0                1
Android v10.1                1
KAI OS                       1
S30+                         1
iOS v14                      1
Android v7.1.2 (Nougat)      1
iOS v11                      1
Name: count, dtype: int64

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
df1['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                                 74
50 MP + 2 MP Dual Rear & 16 MP Front Camera                                53
50 MP + 8 MP Dual Rear & 16 MP Front Camera                                33
50 MP + 2 MP Dual Rear & 32 MP Front Camera                                26
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                       22
50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front Camera                       21
50 MP + 8 MP Dual Rear & 32 MP Front Camera                                21
50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                      19
50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                       18
50 MP + 8 MP Dual Rear & 50 MP Front Camera                                18
50 MP + 50 MP Dual Rear & 50 MP Front Camera                               16
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                      16
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                     16
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                       16
64 MP + 2 MP Dual Rear & 16 MP Front Camera                                13
50 MP + 12 MP + 10 MP Triple Rear & 12 MP Front Camera                     13
50 MP Dual Rear & 8 MP Front Camera                                        12
50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                       12
50 MP + 0.08 MP Dual Rear & 8 MP Front Camera                              10
50 MP Rear & 8 MP Front Camera                                             10
48 MP + 12 MP Dual Rear & 12 MP Front Camera                               10
50 MP + 13 MP Dual Rear & 32 MP Front Camera                               10
13 MP Rear & 5 MP Front Camera                                              9
50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                        9
50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                      9
32 MP Dual Rear & 8 MP Front Camera                                         9
50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                        9
50 MP Dual Rear & 5 MP Front Camera                                         8
50 MP + 2 MP Dual Rear & 5 MP Front Camera                                  8
200 MP Quad Rear & 12 MP Front Camera                                       8
13 MP Dual Rear & 5 MP Front Camera                                         8
12 MP + 12 MP Dual Rear & 12 MP Front Camera                                7
48 MP + 48 MP + 48 MP Triple Rear & 18 MP Front Camera                      7
32 MP Rear & 5 MP Front Camera                                              7
50 MP + 50 MP Dual Rear & 32 MP Front Camera                                6
50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                       6
48 MP + 48 MP + 12 MP Triple Rear & 12 MP Front Camera                      6
50 MP + 50 MP + 8 MP Triple Rear & 16 MP Front Camera                       6
50 MP + 8 MP Dual Rear & 20 MP Front Camera                                 6
108 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                       6
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                       6
108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                       6
13 MP + 0.08 MP Dual Rear & 5 MP Front Camera                               5
200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                       5
64 MP Quad Rear & 32 MP Front Camera                                        5
13 MP Rear & 8 MP Front Camera                                              5
50 MP + 48 MP + 48 MP Triple Rear & 42 MP Front Camera                      5
50 MP + 12 MP + 8 MP Triple Rear & 10 MP Front Camera                       4
50 MP + 2 MP Dual Rear & 50 MP Front Camera                                 4
50 MP + 50 MP + 10 MP Triple Rear & 50 MP Front Camera                      4
50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32 MP Dual Front Camera         4
50 MP Rear & 5 MP Front Camera                                              4
50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front Camera                        4
8 MP Rear & 5 MP Front Camera                                               4
50 MP + 2 MP Triple Rear & 16 MP Front Camera                               4
12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front Camera                       4
32 MP Rear & 8 MP Front Camera                                              4
50 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                       4
64 MP + 8 MP Dual Rear & 13 MP Front Camera                                 4
50 MP + 12 MP Dual Rear & 10 MP Front Camera                                4
64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                        4
50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                       4
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                         4
48 MP Dual Rear & 8 MP Front Camera                                         4
64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                        4
48 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                        4
64 MP + 2 MP Dual Rear & 13 MP Front Camera                                 3
64 MP + 13 MP Dual Rear & 13 MP Front Camera                                3
50 MP + 50 MP + 12 MP Triple Rear & 50 MP Front Camera                      3
48 MP Rear & 12 MP Front Camera                                             3
64 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                        3
64 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                        3
50 MP + 50 MP + 8 MP Triple Rear & 20 MP Front Camera                       3
50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front Camera                        3
48 MP Rear & 18 MP Front Camera                                             3
50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front Camera                       3
200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 10 MP Dual Front Camera        3
108 MP + 2 MP Dual Rear & 16 MP Front Camera                                3
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera          3
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                3
8 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                3
50 MP + Depth Sensor Dual Rear & 5 MP Front Camera                          3
48 MP Quad Rear & 16 MP Front Camera                                        3
50 MP + 50 MP Dual Rear & 16 MP Front Camera                                3
108 MP + 2 MP Dual Rear & 8 MP Front Camera                                 3
50 MP Quad Rear & 32 MP Front Camera                                        3
64 MP + 2 MP Dual Rear & 8 MP Front Camera                                  3
48 MP + 48 MP Dual Rear & 18 MP Front Camera                                2
64 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                       2
64 MP + 8 MP Dual Rear & 50 MP Front Camera                                 2
50 MP + Ultra Wide Dual Rear & 5 MP Front Camera                            2
50 MP + 12 MP Dual Rear & 8 MP Front Camera                                 2
50 MP + 48 MP + 32 MP Triple Rear & 16 MP Front Camera                      2
32 MP + 2 MP Dual Rear & 8 MP Front Camera                                  2
108 MP + 2 MP Dual Rear & 13 MP Front Camera                                2
50 MP + 2 MP Dual Rear & 20 MP Front Camera                                 2
108 MP + 8 MP Dual Rear & 13 MP Front Camera                                2
50 MP + 2 MP Dual Rear & 13 MP Front Camera                                 2
50 MP + 13 MP + 10 MP Triple Rear & 32 MP Front Camera                      2
108 MP + 2 MP Triple Rear & 8 MP Front Camera                               2
50 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                        2
50 MP + 48 MP + 12 MP Triple Rear & 11.1 MP Front Camera                    2
50 MP + 2 MP + 0.08 MP Triple Rear & 50 MP Front Camera                     2
13 MP + 2 MP Dual Rear & 5 MP Front Camera                                  2
Foldable Display, Dual Display                                              2
108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                       2
48 MP Quad Rear & 8 MP Front Camera                                         2
48 MP + Depth Sensor Dual Rear & 8 MP Front Camera                          2
64 MP Quad Rear & 13 MP Front Camera                                        2
108 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                      2
0.3 MP Rear Camera                                                          2
50 MP + 12 MP + 8 MP Triple Rear & 50 MP Front Camera                       2
50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                         2
8 MP Dual Rear & 5 MP Front Camera                                          2
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                        2
48 MP Quad Rear & 13 MP Front Camera                                        2
64 MP + 12 MP + 12 MP Triple Rear & 10 MP Front Camera                      2
64 MP Quad Rear & 16 MP Front Camera                                        2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP Front Camera                      2
64 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera                      2
200 MP + 12 MP Dual Rear & 12 MP Front Camera                               2
50 MP + 8 MP + 8 MP Triple Rear & 16 MP Front Camera                        2
64 MP + 5 MP Dual Rear & 13 MP Front Camera                                 2
50 MP Dual Rear & 13 MP Front Camera                                        2
50 MP + 13 MP + 10 MP Triple Rear & 50 MP Front Camera                      2
64 MP + AI Camera Dual Rear & 13 MP Front Camera                            2
50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                        2
64 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                      1
50 MP + 48 MP + 48 MP Triple Rear & 10.5 MP Front Camera                    1
200 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                     1
48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP Front Camera                  1
108 MP + Macro Dual Rear & 13 MP Front Camera                               1
48 MP + 13 MP Dual Rear & 13 MP Front Camera                                1
50 MP + 48 MP Dual Rear & 10.5 MP Front Camera                              1
108 MP + 5 MP Dual Rear & 16 MP Front Camera                                1
50 MP + 12 MP Dual Rear & 10.8 MP Front Camera                              1
64 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                        1
108 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                       1
108 MP + 13 MP + 2 MP Triple Rear & 50 MP Front Camera                      1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera         1
108 MP + 2 MP Triple Rear & 16 MP Front Camera                              1
48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                       1
108 MP + 5 MP + 2 MP Triple Rear & 50 MP Front Camera                       1
12 MP Quad Rear & 10 MP Front Camera                                        1
8 MP Rear & 8 MP Front Camera                                               1
64 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                       1
50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front Camera                       1
50 MP + Depth Sensor + Macro Triple Rear & 5 MP Front Camera                1
108 MP + 2 MP Dual Rear & 50 MP Front Camera                                1
50 MP + 12 MP Dual Rear & 10.5 MP Front Camera                              1
64 MP + 5 MP + 2 MP Triple Rear & 50 MP Front Camera                        1
50 MP + Depth Sensor Dual Rear & 8 MP Front Camera                          1
12.2 MP + 12 MP Dual Rear & 8 MP Front Camera                               1
50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Front Camera                    1
50 MP + 50 MP + 12 MP Triple Rear & 50 MP + 2 MP Dual Front Camera          1
108 MP Quad Rear & 40 MP Front Camera                                       1
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP Dual Front Camera     1
50 MP + 32 MP + 8 MP Triple Rear & 16 MP Front Camera                       1
108 MP + 5 MP + 2 MP Triple Rear & 16 MP Front Camera                       1
50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera         1
13 MP Rear & Main Front Camera                                              1
64 MP + 50 MP + 50 MP Triple Rear & 16 MP Front Camera                      1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera         1
48 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                        1
64 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                      1
16 MP Rear & 5 MP Front Camera                                              1
2 MP Rear & 0.3 MP Front Camera                                             1
64 MP Quad Rear & 20 MP Front Camera                                        1
48 MP Quad Rear & 20 MP Front Camera                                        1
48 MP + 13 MP + 13 MP Triple Rear & 16 MP Front Camera                      1
108 MP Quad Rear & 32 MP Front Camera                                       1
50 MP + 16 MP + 2 MP Triple Rear & 16 MP Front Camera                       1
64 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                       1
50 MP + 50 MP + 12 MP Triple Rear & 32 MP Front Camera                      1
108 MP + 0.08 MP Dual Rear & 8 MP Front Camera                              1
108 MP + 50 MP + 13 MP Triple Rear & 50 MP Front Camera                     1
50 MP + Ultra Wide + Macro Triple Rear & 8 MP Front Camera                  1
5 MP Rear Camera                                                            1
50 MP Quad Rear & 16 MP Front Camera                                        1
13 MP + 2 MP Dual Rear & 8 MP Front Camera                                  1
5 MP Rear & Main Front Camera                                               1
20 MP + 12 MP Dual Rear & 20 MP Front Camera                                1
64 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                        1
50 MP + 50 MP + 13 MP Triple Rear & 32 MP Front Camera                      1
50 MP + 12 MP + 12 MP Triple Rear & 32 MP Front Camera                      1
108 MP + 8 MP + 2 MP Triple Rear & 50 MP + 8 MP Dual Front Camera           1
64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                        1
64 MP + 13 MP + 5 MP Triple Rear & 24 MP Front Camera                       1
48 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                         1
50 MP Quad Rear & 13 MP Front Camera                                        1
64 MP + 8 MP + 2 MP Triple Rear & 44 MP + 8 MP Dual Front Camera            1
48 MP Quad Rear & 32 MP Front Camera                                        1
48 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                        1
12 MP + 5 MP Dual Rear & 20 MP + 2 MP Dual Front Camera                     1
12 MP + 5 MP Dual Rear & 20 MP Front Camera                                 1
12 MP + 12 MP Dual Rear & 7 MP Front Camera                                 1
50 MP + 5 MP Dual Rear & 8 MP Front Camera                                  1
Dual Display                                                                1
Name: count, dtype: int64

In [ ]:
df1['sim'].value_counts()

sim
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           288
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      201
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster          106
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster               103
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                                65
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                 58
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster     30
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    28
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                      21
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           6
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                            5
Dual Sim, 3G, 4G, Wi-Fi                                        5
Dual Sim                                                       2
Single Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                1
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          1
Name: count, dtype: int64

In [ ]:
df1['processor'].value_counts()

processor
Dimensity 6300, Octa Core, 2.4 GHz Processor                    104
Dimensity 7300, Octa Core, 2.5 GHz Processor                     24
Snapdragon 4 Gen2, Octa Core, 2.2 GHz Processor                  24
Snapdragon 7 Gen3, Octa Core, 2.63 GHz Processor                 23
Snapdragon 8s Gen3, Octa Core, 3 GHz Processor                   18
Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor                 18
Snapdragon 695, Octa Core, 2.2 GHz Processor                     17
Exynos 1380, Octa Core, 2.4 GHz Processor                        17
Snapdragon 7s Gen2, Octa Core, 2.4 GHz Processor                 15
Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor                  15
Dimensity 6100 Plus, Octa Core, 2.2 GHz Processor                15
Snapdragon 6 Gen1, Octa Core, 2.2 GHz Processor                  13
Dimensity 7400, Octa Core, 2.6 GHz Processor                     13
Dimensity 7050, Octa Core, 2.6 GHz Processor                     12
Dimensity 7300 Ultimate, Octa Core, 2.5 GHz Processor            11
Snapdragon 8 Elite, Octa Core, 4.32 GHz Processor                11
Dimensity 7300 Energy, Octa Core, 2.5 GHz Processor              10
Unisoc T7250, Octa Core, 1.8 GHz Processor                       10
Snapdragon 6s Gen3, Octa Core, 2.3 GHz Processor                 10
Apple A19 Pro, Hexa Core Processor                               10
Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor                  10
Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor                 10
Snapdragon 7s Gen 2, Octa Core, 2.4 GHz Processor                10
Dimensity 6400, Octa Core, 2.5 GHz Processor                      9
Bionic A18, Hexa Core, 4.04 GHz Processor                         9
Dimensity 6080, Octa Core, 2.4 GHz Processor                      9
Dimensity 8350, Octa Core, 3.35 GHz Processor                     8
Snapdragon 7 Gen1, Octa Core, 2.4 GHz Processor                   8
Exynos 1480, Octa Core, 2.7 GHz Processor                         8
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor                   8
Helio G85, Octa Core, 2 GHz Processor                             7
Dimensity 7020, Octa Core, 2.2 GHz Processor                      7
Snapdragon 8Elite, Octa Core, 4.47 GHz Processor                  7
Snapdragon 7+ Gen3, Octa Core, 2.8 GHz Processor                  7
Dimensity 9400, Octa Core, 3.63 GHz Processor                     6
Exynos 1330, Octa Core, 2.4 GHz Processor                         6
Dimensity 7025 Ultra, Octa Core, 2.5 GHz Processor                6
Tensor G4, Octa Core, 3.1 GHz Processor                           6
Snapdragon 778G, Octa Core, 2.4 GHz Processor                     6
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor                     6
Dimensity 7300 E, Octa Core, 2.5 GHz Processor                    6
Snapdragon 8 Elite for Galaxy, Octa Core, 4.47 GHz Processor      6
Bionic A18 Pro, Hexa Core, 4.05 GHz Processor                     6
Dimensity 8200, Octa Core, 3.1 GHz Processor                      6
Dimensity 6020, Octa Core, 2.2 GHz Processor                      6
Dimensity 7200, Octa Core, 2.8 GHz Processor                      5
Dimensity 9300 Plus, Octa Core, 3.25 GHz Processor                5
Dimensity 7300 Ultra, Octa Core, 2.5 GHz Processor                5
Bionic A15, Hexa Core, 3.22 GHz Processor                         5
Helio G88, Octa Core, 2 GHz Processor                             5
Exynos 1280, Octa Core, 2.4 GHz Processor                         5
Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor                 5
Dimensity 9200 Plus, Octa Core, 3.35 GHz Processor                5
Exynos 2400, Deca Core, 3.2 GHz Processor                         4
Unisoc T760, Octa Core, 2.2 GHz Processor                         4
Snapdragon 4s Gen2, Octa Core, 2 GHz Processor                    4
Dimensity 7025, Octa Core, 2.5 GHz Processor                      4
Bionic A16, Hexa Core, 3.46 GHz Processor                         4
Dimensity 8450, Octa Core, 3.25 GHz Processor                     4
Unisoc T615, Octa Core, 1.8 GHz Processor                         4
Unisoc T606, Octa Core, 1.6 GHz Processor                         4
Dimensity 9400e, Octa Core, 3.4 GHz Processor                     4
Snapdragon 680, Octa Core, 2.4 GHz Processor                      4
Dimensity 1080, Octa Core, 2.6 GHz Processor                      4
Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor                   4
Tensor G5                                                         3
Dimensity 7200 Pro, Octa Core, 2.8 GHz Processor                  3
Dimensity 8400-MAX, Octa Core, 3.25 GHz Processor                 3
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor                    3
Dimensity 9000, Octa Core, 3.05 GHz Processor                     3
Dimensity 1300, Octa Core, 3 GHz Processor                        3
Octa Core Processor                                               3
Snapdragon 888, Octa Core, 2.84 GHz Processor                     3
Snapdragon  778G , Octa Core, 2.4 GHz Processor                   3
Snapdragon  695, Octa Core, 2.2 GHz Processor                     3
Snapdragon 865, Octa Core, 2.84 GHz Processor                     3
Dimensity 8020, Octa Core, 2.6 GHz Processor                      3
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor                3
Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor                   3
Dimensity 8350 Ultra, Octa Core, 3.35 GHz Processor               3
Dimensity 7300 Plus, Octa Core Processor                          3
Dimensity 9300, Octa Core, 3.25 GHz Processor                     3
Dimensity 7300X, Octa Core, 2.5 GHz Processor                     3
Dimensity  8100, Octa Core, 2.85 GHz Processor                    3
Dimensity 7400 Ultra, Octa Core, 2.6 GHz Processor                3
Snapdragon 7s Gen 3, Octa Core, 2.5 GHz Processor                 3
Exynos 1580, Octa Core, 2.9 GHz Processor                         3
Dimensity 8350 Apex, Octa Core, 3.35 GHz Processor                3
Dimensity 8350 Extreme, Octa Core, 3.35 GHz Processor             3
Dimensity 6400 Max, Octa Core, 2.5 GHz Processor                  3
Snapdragon 7 Gen 4, Octa Core Processor                           3
Snapdragon  680, Octa Core, 2.4 GHz Processor                     3
Snapdragon 870, Octa Core, 3.2 GHz Processor                      3
Snapdragon  888 , Octa Core, 2.84 GHz Processor                   3
Unisoc T603, Octa Core, 1.8 GHz Processor                         2
Dimensity 7030, Octa Core, 2.5 GHz Processor                      2
Snapdragon 6s 4G Gen1, Octa Core, 2.1 GHz Processor               2
Helio G95, Octa Core, 2.05 GHz Processor                          2
Exynos 2500, Deca Core, 3.3 GHz Processor                         2
Tensor G3, Nine-Cores, 3 GHz Processor                            2
Dimensity 800U, Octa Core, 2.4 GHz Processor                      2
Snapdragon 695 , Octa Core, 2.2 GHz Processor                     2
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor                    2
Helio P35, Octa Core, 2.3 GHz Processor                           2
Unisoc UMS9230E, Octa Core, 1.8 GHz Processor                     2
Dimensity 8300 Ultra, Octa Core, 3.35 GHz Processor               2
Exynos 2200, Octa Core, 2.8 GHz Processor                         2
Dimensity 7300 Pro, Octa Core, 2.5 GHz Processor                  2
Snapdragon 4 Gen2 AE, Octa Core, 2.3 GHz Processor                2
Dimensity 8400 Ultra, Octa Core, 3.25 GHz Processor               2
Dimensity 6300, Octa Core Processor                               2
Dimensity 7300, Octa Core Processor                               2
Dimensity 7060, Octa Core, 2.6 GHz Processor                      2
Dimensity 7400, Octa Core, 2.5 GHz Processor                      2
Dimensity 7200 Ultra, Octa Core, 2.8 GHz Processor                2
Apple A19, Hexa Core Processor                                    2
Exynos 2400e, Deca Core, 3.11 GHz Processor                       2
Tensor , Octa Core, 2.8 GHz Processor                             2
Dimensity 8350 Ultimate, Octa Core, 3.35 GHz Processor            2
Unisoc T765, Octa Core, 2.3 GHz Processor                         2
Unisoc T8200, Octa Core Processor                                 2
Snapdragon 782G, Octa Core, 2.7 GHz Processor                     2
Helio G96, Octa Core, 2.05 GHz Processor                          2
Dimensity 1200, Octa Core, 3 GHz Processor                        2
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor                 2
Helio  G85, Octa Core, 2 GHz Processor                            2
Dimensity  810 5G, Octa Core, 2.4 GHz Processor                   2
Dimensity 700 5G, Octa Core, 2.2 GHz Processor                    2
Helio G99, Octa Core, 2.2 GHz Processor                           2
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor                  2
Unisoc T612, Octa Core, 1.8 GHz Processor                         2
Snapdragon  888+, Octa Core, 2.9 GHz Processor                    2
Dimensity 900, Octa Core, 2.4 GHz Processor                       2
Exynos 2400, Octa Core, 3.2 GHz Processor                         2
AMD, Quad Core, 512 MHz Processor                                 2
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor                 2
Dimensit 7020, Octa Core, 2.2 GHz Processor                       2
Snapdragon 636, Octa Core, 1.8 GHz Processor                      2
UNISOC T7100, Octa Core Processor                                 2
Google Tensor, Octa Core, 2.8 GHz Processor                       2
Dimensity 7350 Pro 5G, Octa Core, 3 GHz Processor                 2
Google  Tensor G2, Octa Core, 2.85 GHz Processor                  1
Dimensity 7400X, Octa Core, 2.6 GHz Processor                     1
Unisoc T760, Octa Core Processor                                  1
Tensor G3, Nine Cores, 3 GHz Processor                            1
Snapdragon  732G, Octa Core, 2.3 GHz Processor                    1
Snapdragon 4 Gen 2 AE, Octa Core, 2.3 GHz Processor               1
Helio G81 Ultra, Octa Core, 2 GHz Processor                       1
Google  Tensor, Octa Core Processor                               1
Tensor G3, Nine Core, 3 GHz Processor                             1
Snapdragon 7 Gen1 AE, Octa Core, 2.5 GHz Processor                1
Snapdragon  870 , Octa Core, 3.2 GHz Processor                    1
Exynos 2100, Octa Core, 2.9 GHz Processor                         1
Unisoc 98663a, Octa Core Processor                                1
Exynos 9825, Octa Core, 2.73 GHz Processor                        1
Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor                  1
Dimensity  900, Octa Core, 2.4 GHz Processor                      1
Helio G50, Octa Core Processor                                    1
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor                 1
Unisoc T7100, Octa Core, 1.8 GHz Processor                        1
A13 Bionic, Hexa Core, 2.65 GHz Processor                         1
8 MB RAM, 16 MB inbuilt                                           1
Dimensity 8050, Octa Core, 3 GHz Processor                        1
Google Tensor G2, Octa Core, 2.85 GHz Processor                   1
Dimensity  900, Octa Core, 2 GHz Processor                        1
Snapdragon 695 5G, Octa Core, 2.2 GHz Processor                   1
Snapdragon 7+ Gen2, Octa Core, 2.91 GHz Processor                 1
Unisoc T765, Octa Core Processor                                  1
Dimensity 930, Octa Core, 2.2 GHz Processor                       1
Tensor G2, Octa Core, 2.85 GHz Processor                          1
Dimensity 8200 Ultimate, Octa Core, 3.1 GHz Processor             1
Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor                 1
Unisoc T7225, Octa Core, 1.8 GHz Processor                        1
Helio G50, Octa Core, 2.2 GHz Processor                           1
Exynos 850, Octa Core, 2 GHz Processor                            1
Helio  G90T, Octa Core, 2.05 GHz Processor                        1
Dual Core, 1 GHz Processor                                        1
Unisoc 6531F                                                      1
Snapdragon 6s Gen1 4G, Octa Core Processor                        1
Exynos 1280 , Octa Core, 2.4 GHz Processor                        1
Helio G36, Octa Core, 2.2 GHz Processor                           1
Unisoc 9863A, Octa Core Processor                                 1
Snapdragon 660, Octa Core, 2.2 GHz Processor                      1
Dimensity 1000+, Octa Core, 2.6 GHz Processor                     1
Snapdragon  662 , Octa Core, 2 GHz Processor                      1
Dimensity 9200, Octa Core, 3.05 GHz Processor                     1
Snapdragon 860, Octa Core, 2.96 GHz Processor                     1
Tiger T606, Octa Core, 1.6 GHz Processor                          1
Helio G70, Octa Core, 2 GHz Processor                             1
Tiger T612, Octa Core, 1.82 GHz Processor                         1
Exynos 1330, Octa Core Processor                                  1
Helio G91, Octa Core, 2 GHz Processor                             1
Snapdragon 4 Gen1, Octa Core, 2 GHz Processor                     1
Dimensity 810 5G, Octa Core, 2.4 GHz Processor                    1
Helio G35, Octa Core, 2.3 GHz Processor                           1
Snapdragon  870, Octa Core, 3.2 GHz Processor                     1
Helio G37, Octa Core, 2.3 GHz Processor                           1
Exynos  1280, Octa Core, 2.4 GHz Processor                        1
Dimensity  9000, Octa Core, 3.05 GHz Processor                    1
Dimensity 700 , Octa Core, 2.2 GHz Processor                      1
Snapdragon 460, Octa Core, 1.8 GHz Processor                      1
Snapdragon  4 Gen 1, Octa Core, 2 GHz Processor                   1
Helio  G99, Octa Core, 2.2 GHz Processor                          1
Dimensity 800U , Octa Core, 2.4 GHz Processor                     1
Snapdragon  720G, Octa Core, 2.3 GHz Processor                    1
Snapdragon 732G , Octa Core, 2.3 GHz Processor                    1
Helio G95, Octa Core, 2 GHz Processor                             1
Exynos  2100, Octa Core, 2.9 GHz Processor                        1
Exynos  990, Octa Core, 2.73 GHz Processor                        1
Bionic A14, Hexa Core, 3.1 GHz Processor                          1
Snapdragon 765G , Octa Core, 2.4 GHz Processor                    1
Exynos  9611, Octa Core, 2.3 GHz Processor                        1
Snapdragon 665, Octa Core, 2 GHz Processor                        1
Snapdragon  665, Octa Core, 2 GHz Processor                       1
Snapdragon 730, Octa Core, 2.2 GHz Processor                      1
Snapdragon MSM8917, Quad Core, 1.4 GHz Processor                  1
Apple A11, Hexa Core, 2.39 GHz Processor                          1
UNISOC 9863A, Octa Core Processor                                 1
Unisoc SC9863A, Octa Core, 1.6 GHz Processor                      1
Name: count, dtype: int64

In [ ]:
df1['display'].value_counts()

display
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          74
6.77 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole          48
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           42
6.67 inches, 720 x 1604 px, 120 Hz Display with Punch Hole           28
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole          21
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole          21
6.78 inches, 1264 x 2780 px, 120 Hz Display with Punch Hole          18
6.74 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch      16
6.67 inches, 720 x 1600 px, 120 Hz Display with Punch Hole           15
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          14
6.83 inches, 1272 x 2800 px, 120 Hz Display with Punch Hole          14
6.72 inches, 1080 x 2408 px, 120 Hz Display with Punch Hole          14
6.7 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           11
6.88 inches, 720 x 1640 px, 120 Hz Display with Water Drop Notch     10
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           10
6.78 inches, 1260 x 2800 px, 144 Hz Display with Punch Hole           9
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            9
6.8 inches, 1280 x 2800 px, 144 Hz Display with Punch Hole            9
6.8 inches, 1280 x 2800 px, 120 Hz Display with Punch Hole            9
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           9
6.79 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            9
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            8
6.7 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole            8
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       8
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            8
6.7 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch       8
6.59 inches, 1256 x 2760 px, 120 Hz Display with Punch Hole           8
6.1 inches, 1170 x 2532 px Display with Small Notch                   7
6.9 inches, 1320 x 2868 px, 120 Hz Display with Dynamic Island        7
6.2 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            7
6.67 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           7
6.78 inches, 1224 x 2720 px, 144 Hz Display with Punch Hole           7
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            7
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            7
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           7
6.57 inches, 1080 x 2372 px, 120 Hz Display with Punch Hole           6
6.74 inches, 1240 x 2772 px, 120 Hz Display with Punch Hole           6
6.7 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch      6
6.78 inches, 1080 x 2436 px, 144 Hz Display with Punch Hole           6
6.78 inches, 1080 x 2436 px, 120 Hz Display with Punch Hole           6
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            6
6.3 inches, 1206 x 2622 px, 120 Hz Display with Dynamic Island        6
6.7 inches, 720 x 1600 px Display with Water Drop Notch               6
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             6
6.9 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole            6
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           5
6.68 inches, 720 x 1608 px, 120 Hz Display with Punch Hole            5
6.75 inches, 720 x 1600 px Display with Water Drop Notch              5
6.67 inches, 720 x 1604 px, 90 Hz Display with Punch Hole             5
6.75 inches, 720 x 1600 px, 120 Hz Display with Water Drop Notch      5
6.7 inches, 1290 x 2796 px Display with Dynamic Island                5
6.67 inches, 720 x 1612 px, 120 Hz Display with Punch Hole            5
6.7 inches, 1084 x 2412 px, 120 Hz Display with Punch Hole            5
6.82 inches, 1440 x 3168 px, 120 Hz Display with Punch Hole           5
6.55 inches, 1236 x 2750 px, 120 Hz Display with Punch Hole           4
6.75 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       4
6.88 inches, 720 x 1650 px, 120 Hz Display with Water Drop Notch      4
6.5 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch      4
6.8 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            4
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole            4
6.73 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           4
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           4
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           4
6.74 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           4
6.5 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             3
6.77 inches, 1080 x 2392 px, 144 Hz Display with Punch Hole           3
6.7 inches, 1200 x 2664 px, 120 Hz Display with Punch Hole            3
6.7 inches, 1220 x 2712 px, 144 Hz Display with Punch Hole            3
6.6 inches, 720 x 1612 px, 90 Hz Display with Punch Hole              3
6.5 inches, 720 x 1600 px, 90 Hz Display with Punch Hole              3
6.75 inches, 1600 x 720 px Display with Water Drop Notch              3
6.5 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch       3
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             3
6.9 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            3
6.67 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            3
8 inches, 1968 x 2184 px, 120 Hz Display with Punch Hole              3
6.9 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            3
6.8 inches, 1344 x 2992 px, 120 Hz Display with Punch Hole            3
6.72 inches, 1080 x 2392 px, 120 Hz Display with Punch Hole           3
6.5 inches, 1260 x 2736 px Display with Dynamic Island                3
6.79 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           3
6.74 inches, 720 x 1600 px, 90 Hz Display                             3
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.8 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            3
6.3 inches, 1080 x 2424 px, 120 Hz Display with Punch Hole            3
6.83 inches, 1272 x 2800 px, 144 Hz Display with Punch Hole           3
6.1 inches, 1179 x 2556 px Display with Dynamic Island Display        3
6.45 inches, 1080 x 2340 px, 90 Hz Display with Water Drop Notch      3
6.55 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            3
6.58 inches, 1080 x 2408 px Display with Water Drop Notch             3
6.43 inches, 1080 x 2400 px Display with Punch Hole                   3
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        3
6.71 inches, 720 x 1650 px, 90 Hz Display with Water Drop Notch       3
6.74 inches, 720 x 1600 px Display with Water Drop Notch              3
6.7 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             3
6.7 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        3
6.55 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           3
6.9 inches, 1080 x 2520 px, 120 Hz Display with Punch Hole            2
6.51 inches, 720 x 1600 px Display with Water Drop Notch              2
6.59 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           2
6.1 inches, 1179 x 2556 px Display with Dynamic Island                2
6.32 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           2
6.82 inches, 1440 x 3168 px, 144 Hz Display with Punch Hole           2
6.3 inches, 1206 x 2622 px, 120 Hz Display with Small Notch           2
6.57 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           2
6.31 inches, 1216 x 2640 px, 120 Hz Display with Punch Hole           2
6.38 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            2
6.8 inches, 1440 x 3088 px, 120 Hz Display with Punch Hole            2
6.67 inches, 1080 x 1920 px, 120 Hz Display with Punch Hole           2
6.1 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            2
6.71 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           2
6.36 inches, 1200 x 2670 px, 120 Hz Display with Punch Hole           2
6.78 inches, 1080 x 2406 px, 120 Hz Display with Punch Hole           2
6.3 inches, 1280 x 2856 px, 120 Hz Display with Punch Hole            2
6.68 inches, 720 x 1620 px, 120 Hz Display with Water Drop Notch      2
6.83 inches, 1280 x 2772 px, 120 Hz Display with Punch Hole           2
6.74 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             2
6.56 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             2
6.74 inches, 720 x 1612 px, 120 Hz Display with Punch Hole            2
6.53 inches, 1080 x 2340 px Display with Water Drop Notch             2
6.58 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      2
6.4 inches, 1080 x 2400 px Display with Punch Hole                    2
6.38 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      2
7.6 inches, 1812 x 2176 px, 120 Hz Display with Punch Hole            2
5.99 inches, 1080 x 2160 px Display                                   2
6.72 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            2
6.56 inches, 1080 x 2376 px, 120 Hz Display with Punch Hole           2
6.78 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           2
8.03 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole           2
6.67 inches, 1080 x 2400 px Display with Punch Hole                   2
6.47 inches, 1080 x 2400 px Display with Punch Hole                   2
6.6 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             2
6.7 inches, 1080 x 2400 px Display with Punch Hole                    2
6.43 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             2
6.78 inches, 1200 x 2652 px, 120 Hz Display with Punch Hole           2
6.67 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           2
6.78 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole           2
6.75 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            2
6.56 inches, 720 x 1612 px, 90 Hz Display with Punch Hole             2
6.2 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            2
6.7 inches, 1344 x 2992 px, 120 Hz Display with Punch Hole            1
6.78 inches, 1224 x 2700 px Display with Punch Hole                   1
6.74 inches, 720 x 1600 px, 120 Hz Display with Punch Hole            1
6.4 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole            1
6.9 inches, 1080 x 2640 px, 165 Hz Display with Punch Hole            1
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            1
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            1
6.1 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.96 inches, 1224 x 2992 px, 165 Hz Display with Punch Hole           1
7.6 inches, 1856 x 2160 px, 120 Hz Display with Punch Hole            1
6.67 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             1
6.1 inches, 828 x 1792 px Display with Large Notch                    1
6.75 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             1
2.4 inches, 240 x 320 px Display                                      1
6.7 inches, 1284 x 2778 px Display with Small Notch                   1
6.3 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.44 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      1
6.7 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            1
8.03 inches, 2152 x 2076 px, 120 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2400 px Display with Water Drop Notch              1
6.78 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2408 px, 120 Hz Display with Punch Hole            1
6.67 inches, 1600 x 720 px, 120 Hz Display with Punch Hole            1
6.8 inches, 1440 x 3040 px Display with Punch Hole                    1
6.7 inches, 1080 x 2412 px Display with Small Notch                   1
6.6 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch       1
6.78 inches, 1440 x 3168 px, 120 Hz Display with Punch Hole           1
6.77 inches, 1264 x 2780 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1220 x 2712 px, 120 Hz Display                           1
6.78 inches, 1224 x 2700 px, 120 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole             1
6.14 inches, 1080 x 2400 px Display with Punch Hole                   1
3 inches, 384 x 216 px Display                                        1
6.6 inches, 1080 x 2408 px Display with Water Drop Notch              1
2.4 inches, 320 x 240 px Display                                      1
6.74 inches, 720 x 1650 px, 90 Hz Display with Punch Hole             1
6.55 inches, 1080 x 2400 px, 144 Hz Display                           1
6.44 inches, 1080 x 2404 px, 90 Hz Display with Water Drop Notch      1
6.67 inches, 720 x 1612 px, 90 Hz Display with Punch Hole             1
6.6 inches, 1080 x 2340 px, 120 Hz Display with Water Drop Notch      1
7.85 inches, 2000 x 2296 px, 120 Hz Display                           1
6.78 inches, 1220 x 2652 px, 120 Hz Display with Punch Hole           1
6.6 inches, 2408 x 1080 px Display with Water Drop Notch              1
6.74 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.72 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.6 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch        1
2.8 inches, 240 x 320 px Display                                      1
6.7 inches, 720 x 1600 px, 90 Hz Display with Punch Hole              1
6.56 inches, 1600 x 720 px Display with Water Drop Notch              1
7.82 inches, 2268 x 2440 px, 120 Hz Display with Punch Hole           1
3 inches Display                                                      1
6.58 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.56 inches, 720 x 1612 px Display with Water Drop Notch              1
6.58 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      1
6.6 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole             1
6.55 inches, 720 x 1612 px Display with Water Drop Notch              1
6.78 inches, 2400 x 1200 px, 120 Hz Display with Punch Hole           1
6.5 inches, 720 x 1600 px Display with Water Drop Notch               1
6.7 inches, 2400 x 1080 px Display with Punch Hole                    1
6.6 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            1
6.44 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
6.56 inches, 1080 x 2376 px, 90 Hz Display with Small Notch           1
6.78 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           1
6.51 inches, 1600 x 720 px Display with Water Drop Notch              1
6.1 inches, 1170 x 2532 px Display with Large Notch                   1
6.78 inches, 1080 x 2448 px, 144 Hz Display                           1
6.44 inches, 1080 x 2400 px Display with Small Notch                  1
6.3 inches, 1080 x 2280 px Display with Water Drop Notch              1
6.08 inches, 720 x 1560 px Display with Water Drop Notch              1
6.5 inches, 1080 x 2340 px Display with Punch Hole                    1
5 inches, 720 x 1280 px Display                                       1
6.26 inches, 1080 x 2280 px Display with Large Notch                  1
5.5 inches, 1080 x 1920 px Display                                    1
6.6 inches, 720 x 1612 px Display with Water Drop Notch               1
Name: count, dtype: int64